# Generated by Django 5.0 on 2023-12-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_perpus', '0003_historicalanggota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalAnggota',
        ),
    ]
