# Generated by Django 5.0 on 2023-12-13 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perpus', '0004_delete_historicalanggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
