# Generated by Django 5.0 on 2023-12-13 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perpus', '0005_anggota_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
