# Generated by Django 5.0 on 2023-12-14 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_perpus', '0008_petugas_created_at_petugas_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
